// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkhIJE4Iq33oX1_lfjUO0jalzH-anDD90',
    appId: '1:187538868842:web:5d5e1904b3ca9040979813',
    messagingSenderId: '187538868842',
    projectId: 'temp8-80d19',
    authDomain: 'temp8-80d19.firebaseapp.com',
    storageBucket: 'temp8-80d19.firebasestorage.app',
    measurementId: 'G-LJR89D7CXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZixpl4lOFrThwQ1IeLtJhQCsCxpJ2jw',
    appId: '1:187538868842:android:2e8996e91e5fb652979813',
    messagingSenderId: '187538868842',
    projectId: 'temp8-80d19',
    storageBucket: 'temp8-80d19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTyGJjGuSX_mYPlyiwGqn8m9w0I2HRvYo',
    appId: '1:187538868842:ios:f0426b4f449da208979813',
    messagingSenderId: '187538868842',
    projectId: 'temp8-80d19',
    storageBucket: 'temp8-80d19.firebasestorage.app',
    iosBundleId: 'com.example.template8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTyGJjGuSX_mYPlyiwGqn8m9w0I2HRvYo',
    appId: '1:187538868842:ios:f0426b4f449da208979813',
    messagingSenderId: '187538868842',
    projectId: 'temp8-80d19',
    storageBucket: 'temp8-80d19.firebasestorage.app',
    iosBundleId: 'com.example.template8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkhIJE4Iq33oX1_lfjUO0jalzH-anDD90',
    appId: '1:187538868842:web:730f942ef4e37f0f979813',
    messagingSenderId: '187538868842',
    projectId: 'temp8-80d19',
    authDomain: 'temp8-80d19.firebaseapp.com',
    storageBucket: 'temp8-80d19.firebasestorage.app',
    measurementId: 'G-NW8TFB8PM6',
  );
}
